ALTER TABLE public.deals ADD COLUMN IF NOT EXISTS buyer_reported_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.deals ADD COLUMN IF NOT EXISTS buyer_urged_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.deals ADD COLUMN IF NOT EXISTS seller_reported_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.deals ADD COLUMN IF NOT EXISTS seller_urged_at TIMESTAMP WITH TIME ZONE;
